---
engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  eslint:
    enabled: true
  fixme:
    enabled: true
    exclude_fingerprints:
    - ac297346e9db41fdbef7644b8e9c5c43
ratings:
  paths:
  - "**.css"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths:
- config/
- test/
- "web/theme/js/bootstrap-tour.js"
- "web/theme/js/bootstrap-tour.min.js"
- "web/theme/js/bootstrap.js"
- "web/theme/js/bootstrap.min.js"
- "web/theme/js/pnotify.custom.min.js"
- "web/theme/fonts/*"
- "web/theme/css/bootstrap-theme.css"
- "web/theme/css/bootstrap-theme.min.css"
- "web/theme/css/bootstrap-tour.css"
- "web/theme/css/bootstrap-tour.min.css"
- "web/theme/css/bootstrap.css"
- "web/theme/css/bootstrap.min.css"
- "web/theme/css/pnotify.custom.min.css"
- "apidocs/**"
